name: CI/CD

on:
  push:
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Build
        run: |
          npm install
          npm run build
        
      - name: GitHubAssistantBot Preprocess
        id: preprocess_commits
        if: success() || failure()
        run: |
          commits_json=$(cat <<EOL
          ${{toJson(github.event.commits)}}
          EOL
          )

          echo "commits=$(echo "$commits_json" | jq -c '[.[] | {message: .message, url: .url}]' || echo "[]")" >> $GITHUB_OUTPUT

      - name: GitHubAssistantBot
        if: success() || failure()
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://node-red.geeken.me/github_assistant_bot'
          data: |
            {
              "key": "${{secrets.ASSISTANT_BOT_KEY}}",
              "actor": "${{github.actor}}",
              "changes": "https://github.com/${{github.repository}}/commit/${{github.sha}}",
              "commits": ${{steps.preprocess_commits.outputs.commits}},
              "event": "${{github.event_name}}",
              "reference": "${{github.ref_name}}",
              "report": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}",
              "repository": "${{github.repository}}",
              "status": "${{job.status}}"
            }
